// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: personal_usage.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPersonalTaskSummary = `-- name: GetPersonalTaskSummary :one
SELECT
    COUNT(*)::bigint AS task_count,
    COUNT(*) FILTER (WHERE atq.status = 'completed')::bigint AS completed_count,
    COUNT(*) FILTER (WHERE atq.status = 'failed')::bigint AS failed_count,
    COALESCE(
        SUM(EXTRACT(EPOCH FROM (atq.completed_at - atq.started_at)))::bigint,
        0
    )::bigint AS runtime_seconds
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
WHERE a.workspace_id = $1
  AND atq.initiator_user_id = $2
  AND atq.status IN ('completed', 'failed')
  AND atq.completed_at >= $3::timestamptz
  AND atq.completed_at <  $4::timestamptz
`

type GetPersonalTaskSummaryParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type GetPersonalTaskSummaryRow struct {
	TaskCount      int64 `json:"task_count"`
	CompletedCount int64 `json:"completed_count"`
	FailedCount    int64 `json:"failed_count"`
	RuntimeSeconds int64 `json:"runtime_seconds"`
}

// Task-count / run-time / success-rate components over the current user's
// terminal tasks in [since, until). Computed off `agent_task_queue` alone so
// terminal tasks without a `task_usage` row still count. Run time only
// accumulates tasks that actually started (queued-expired tasks have no
// duration) — SUM over a NULL delta is NULL, so a window of only
// never-started tasks yields 0.
func (q *Queries) GetPersonalTaskSummary(ctx context.Context, arg GetPersonalTaskSummaryParams) (GetPersonalTaskSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPersonalTaskSummary,
		arg.WorkspaceID,
		arg.UserID,
		arg.Since,
		arg.Until,
	)
	var i GetPersonalTaskSummaryRow
	err := row.Scan(
		&i.TaskCount,
		&i.CompletedCount,
		&i.FailedCount,
		&i.RuntimeSeconds,
	)
	return i, err
}

const getPersonalUsageSummary = `-- name: GetPersonalUsageSummary :one

SELECT
    COALESCE(SUM(tu.input_tokens), 0)::bigint       AS input_tokens,
    COALESCE(SUM(tu.output_tokens), 0)::bigint      AS output_tokens,
    COALESCE(SUM(tu.cache_read_tokens), 0)::bigint  AS cache_read_tokens,
    COALESCE(SUM(tu.cache_write_tokens), 0)::bigint AS cache_write_tokens,
    COALESCE(SUM(tu.cost_usd_ticks), 0)::bigint AS cost_usd_ticks,
    COALESCE(SUM(tu.input_tokens)       FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_input_tokens,
    COALESCE(SUM(tu.output_tokens)      FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_output_tokens,
    COALESCE(SUM(tu.cache_read_tokens)  FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_cache_read_tokens,
    COALESCE(SUM(tu.cache_write_tokens) FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_cache_write_tokens
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
JOIN task_usage tu ON tu.task_id = atq.id
WHERE a.workspace_id = $1
  AND atq.initiator_user_id = $2
  AND atq.status IN ('completed', 'failed')
  AND atq.completed_at >= $3::timestamptz
  AND atq.completed_at <  $4::timestamptz
`

type GetPersonalUsageSummaryParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type GetPersonalUsageSummaryRow struct {
	InputTokens              int64 `json:"input_tokens"`
	OutputTokens             int64 `json:"output_tokens"`
	CacheReadTokens          int64 `json:"cache_read_tokens"`
	CacheWriteTokens         int64 `json:"cache_write_tokens"`
	CostUsdTicks             int64 `json:"cost_usd_ticks"`
	UncostedInputTokens      int64 `json:"uncosted_input_tokens"`
	UncostedOutputTokens     int64 `json:"uncosted_output_tokens"`
	UncostedCacheReadTokens  int64 `json:"uncosted_cache_read_tokens"`
	UncostedCacheWriteTokens int64 `json:"uncosted_cache_write_tokens"`
}

// Personal-dimension usage dashboard queries (CLO-206 / CLO-212).
//
// Eight endpoints back the developer's personal dashboard page
// (`GET /api/dashboard/personal/*`). Unlike the workspace rollups, these
// aggregate RAW `task_usage` joined to `agent_task_queue` -- the hourly
// rollup (`task_usage_hourly`) carries no user dimension, and local
// deployment scale makes a raw scan cheap (CLO-206 §6).
//
// 口径 (definitions of record -- data spec CALC-CLO-211):
//   - Attribution: a task belongs to the user who INITIATED it, via
//     `agent_task_queue.initiator_user_id`. NULL initiators (autopilot /
//     system runs) are never attributed, and never join the team ranking.
//   - Scope: terminal tasks only (`status IN ('completed','failed')`),
//     windowed on `completed_at` -- the same anchor the workspace
//     run-time / failure rollups use, so every panel on the page agrees.
//   - Tokens / cost: only the `task_usage` rows of those terminal tasks.
//     Cost is the split convention from migration 213:
//     `cost_usd_ticks` (provider-reported, 1e-10 USD) + the
//     `uncosted_*_tokens` (rows the provider did not price, to be
//     estimated client-side from the static rate table).
//   - Success rate denominator: completed + failed terminal tasks.
//     Tasks that expired in the queue without starting are still
//     `failed`, so they DO count (same as ListDashboardFailuresDaily).
//   - Run time: terminal tasks with BOTH started_at and completed_at;
//     queued-expired tasks have no duration and only count as failures.
//
// All personal queries are scoped to the caller's workspace via the
// `agent` join, so "我的数据" and "团队排名" stay on the same team
// population.
// Token + cost split over the current user's terminal tasks in [since, until).
// Returns exactly one row (all zeros when the window is empty) so the handler
// can build a KPI payload without special-casing ErrNoRows.
func (q *Queries) GetPersonalUsageSummary(ctx context.Context, arg GetPersonalUsageSummaryParams) (GetPersonalUsageSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPersonalUsageSummary,
		arg.WorkspaceID,
		arg.UserID,
		arg.Since,
		arg.Until,
	)
	var i GetPersonalUsageSummaryRow
	err := row.Scan(
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.CostUsdTicks,
		&i.UncostedInputTokens,
		&i.UncostedOutputTokens,
		&i.UncostedCacheReadTokens,
		&i.UncostedCacheWriteTokens,
	)
	return i, err
}

const listPersonalErrors = `-- name: ListPersonalErrors :many
SELECT
    CASE
        WHEN atq.status = 'failed'
            THEN COALESCE(NULLIF(atq.failure_reason, ''), 'unclassified')
        ELSE ''
    END AS failure_reason,
    COUNT(*)::bigint AS task_count
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
WHERE a.workspace_id = $1
  AND atq.initiator_user_id = $2
  AND atq.status IN ('completed', 'failed')
  AND atq.completed_at >= $3::timestamptz
  AND atq.completed_at <  $4::timestamptz
GROUP BY 1
ORDER BY task_count DESC, failure_reason
`

type ListPersonalErrorsParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListPersonalErrorsRow struct {
	FailureReason string `json:"failure_reason"`
	TaskCount     int64  `json:"task_count"`
}

// Per-failure-reason terminal-task counts over the current user's tasks in
// the window. Same succeeded-bucket convention as the workspace failure
// rollups: `failure_reason = ”` carries the completed count (the
// denominator the client needs for an error rate). Failed rows with a NULL /
// empty reason collapse into `unclassified`.
func (q *Queries) ListPersonalErrors(ctx context.Context, arg ListPersonalErrorsParams) ([]ListPersonalErrorsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalErrors,
		arg.WorkspaceID,
		arg.UserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalErrorsRow{}
	for rows.Next() {
		var i ListPersonalErrorsRow
		if err := rows.Scan(&i.FailureReason, &i.TaskCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalFailuresTrendDaily = `-- name: ListPersonalFailuresTrendDaily :many
SELECT
    DATE(atq.completed_at AT TIME ZONE $1::text) AS date,
    COUNT(*) FILTER (WHERE atq.status = 'completed')::bigint AS completed_count,
    COUNT(*) FILTER (WHERE atq.status = 'failed')::bigint AS failed_count
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
WHERE a.workspace_id = $2
  AND atq.initiator_user_id = $3
  AND atq.status IN ('completed', 'failed')
  AND atq.completed_at IS NOT NULL
  AND atq.completed_at >= $4::timestamptz
  AND atq.completed_at <  $5::timestamptz
GROUP BY 1
ORDER BY 1
`

type ListPersonalFailuresTrendDailyParams struct {
	Tz          string             `json:"tz"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListPersonalFailuresTrendDailyRow struct {
	Date           pgtype.Date `json:"date"`
	CompletedCount int64       `json:"completed_count"`
	FailedCount    int64       `json:"failed_count"`
}

// Per-calendar-day (viewer tz) completed/failed counts over the current
// user's terminal tasks. Feeds the failure-rate trend line (interface 6);
// the day axis must line up with the usage / runtime trends, so the same
// window, tz and completed_at anchor apply.
func (q *Queries) ListPersonalFailuresTrendDaily(ctx context.Context, arg ListPersonalFailuresTrendDailyParams) ([]ListPersonalFailuresTrendDailyRow, error) {
	rows, err := q.db.Query(ctx, listPersonalFailuresTrendDaily,
		arg.Tz,
		arg.WorkspaceID,
		arg.UserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalFailuresTrendDailyRow{}
	for rows.Next() {
		var i ListPersonalFailuresTrendDailyRow
		if err := rows.Scan(&i.Date, &i.CompletedCount, &i.FailedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalFailuresTrendHourly = `-- name: ListPersonalFailuresTrendHourly :many
SELECT
    DATE_TRUNC('hour', atq.completed_at AT TIME ZONE $1::text)::timestamp AS bucket,
    COUNT(*) FILTER (WHERE atq.status = 'completed')::bigint AS completed_count,
    COUNT(*) FILTER (WHERE atq.status = 'failed')::bigint AS failed_count
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
WHERE a.workspace_id = $2
  AND atq.initiator_user_id = $3
  AND atq.status IN ('completed', 'failed')
  AND atq.completed_at IS NOT NULL
  AND atq.completed_at >= $4::timestamptz
  AND atq.completed_at <  $5::timestamptz
GROUP BY 1
ORDER BY 1
`

type ListPersonalFailuresTrendHourlyParams struct {
	Tz          string             `json:"tz"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListPersonalFailuresTrendHourlyRow struct {
	Bucket         pgtype.Timestamp `json:"bucket"`
	CompletedCount int64            `json:"completed_count"`
	FailedCount    int64            `json:"failed_count"`
}

// Per-hour (viewer tz) completed/failed counts over the current user's
// terminal tasks. Feeds the failure-rate trend for the `today` range.
func (q *Queries) ListPersonalFailuresTrendHourly(ctx context.Context, arg ListPersonalFailuresTrendHourlyParams) ([]ListPersonalFailuresTrendHourlyRow, error) {
	rows, err := q.db.Query(ctx, listPersonalFailuresTrendHourly,
		arg.Tz,
		arg.WorkspaceID,
		arg.UserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalFailuresTrendHourlyRow{}
	for rows.Next() {
		var i ListPersonalFailuresTrendHourlyRow
		if err := rows.Scan(&i.Bucket, &i.CompletedCount, &i.FailedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalRankMembers = `-- name: ListPersonalRankMembers :many
SELECT
    atq.initiator_user_id AS user_id,
    COALESCE(SUM(tu.input_tokens + tu.output_tokens + tu.cache_read_tokens + tu.cache_write_tokens), 0)::bigint AS tokens
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
LEFT JOIN task_usage tu ON tu.task_id = atq.id
WHERE a.workspace_id = $1
  AND atq.status IN ('completed', 'failed')
  AND atq.completed_at >= $2::timestamptz
  AND atq.completed_at <  $3::timestamptz
  AND atq.initiator_user_id IS NOT NULL
GROUP BY atq.initiator_user_id
ORDER BY tokens DESC, atq.initiator_user_id
`

type ListPersonalRankMembersParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListPersonalRankMembersRow struct {
	UserID pgtype.UUID `json:"user_id"`
	Tokens int64       `json:"tokens"`
}

// Every workspace initiator with ≥1 terminal task in the window and their
// token total. The handler computes the caller's competition rank, the
// "beat X% of members" figure, and the anonymous team average / median in
// Go. Privacy boundary (CLO-206 §5): this row set stays server-side — the
// wire response carries ONLY the caller's own numbers plus anonymous
// aggregates, never another member's identity or totals.
func (q *Queries) ListPersonalRankMembers(ctx context.Context, arg ListPersonalRankMembersParams) ([]ListPersonalRankMembersRow, error) {
	rows, err := q.db.Query(ctx, listPersonalRankMembers, arg.WorkspaceID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalRankMembersRow{}
	for rows.Next() {
		var i ListPersonalRankMembersRow
		if err := rows.Scan(&i.UserID, &i.Tokens); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalRuntimeTrendDaily = `-- name: ListPersonalRuntimeTrendDaily :many
SELECT
    DATE(atq.completed_at AT TIME ZONE $1::text) AS date,
    COALESCE(
        SUM(EXTRACT(EPOCH FROM (atq.completed_at - atq.started_at)))::bigint,
        0
    )::bigint AS total_seconds,
    COUNT(*)::bigint AS task_count
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
WHERE a.workspace_id = $2
  AND atq.initiator_user_id = $3
  AND atq.status IN ('completed', 'failed')
  AND atq.started_at IS NOT NULL
  AND atq.completed_at IS NOT NULL
  AND atq.completed_at >= $4::timestamptz
  AND atq.completed_at <  $5::timestamptz
GROUP BY 1
ORDER BY 1
`

type ListPersonalRuntimeTrendDailyParams struct {
	Tz          string             `json:"tz"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListPersonalRuntimeTrendDailyRow struct {
	Date         pgtype.Date `json:"date"`
	TotalSeconds int64       `json:"total_seconds"`
	TaskCount    int64       `json:"task_count"`
}

// Per-calendar-day (viewer tz) total run time + task counts over the current
// user's terminal tasks. Powers the daily/weekly total-run-time trend.
func (q *Queries) ListPersonalRuntimeTrendDaily(ctx context.Context, arg ListPersonalRuntimeTrendDailyParams) ([]ListPersonalRuntimeTrendDailyRow, error) {
	rows, err := q.db.Query(ctx, listPersonalRuntimeTrendDaily,
		arg.Tz,
		arg.WorkspaceID,
		arg.UserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalRuntimeTrendDailyRow{}
	for rows.Next() {
		var i ListPersonalRuntimeTrendDailyRow
		if err := rows.Scan(&i.Date, &i.TotalSeconds, &i.TaskCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalRuntimeTrendHourly = `-- name: ListPersonalRuntimeTrendHourly :many
SELECT
    DATE_TRUNC('hour', atq.completed_at AT TIME ZONE $1::text)::timestamp AS bucket,
    COALESCE(
        SUM(EXTRACT(EPOCH FROM (atq.completed_at - atq.started_at)))::bigint,
        0
    )::bigint AS total_seconds,
    COUNT(*)::bigint AS task_count
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
WHERE a.workspace_id = $2
  AND atq.initiator_user_id = $3
  AND atq.status IN ('completed', 'failed')
  AND atq.started_at IS NOT NULL
  AND atq.completed_at IS NOT NULL
  AND atq.completed_at >= $4::timestamptz
  AND atq.completed_at <  $5::timestamptz
GROUP BY 1
ORDER BY 1
`

type ListPersonalRuntimeTrendHourlyParams struct {
	Tz          string             `json:"tz"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListPersonalRuntimeTrendHourlyRow struct {
	Bucket       pgtype.Timestamp `json:"bucket"`
	TotalSeconds int64            `json:"total_seconds"`
	TaskCount    int64            `json:"task_count"`
}

// Per-hour (viewer tz) total run time + task counts over the current user's
// terminal tasks. Powers the total-run-time trend for the `today` range.
func (q *Queries) ListPersonalRuntimeTrendHourly(ctx context.Context, arg ListPersonalRuntimeTrendHourlyParams) ([]ListPersonalRuntimeTrendHourlyRow, error) {
	rows, err := q.db.Query(ctx, listPersonalRuntimeTrendHourly,
		arg.Tz,
		arg.WorkspaceID,
		arg.UserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalRuntimeTrendHourlyRow{}
	for rows.Next() {
		var i ListPersonalRuntimeTrendHourlyRow
		if err := rows.Scan(&i.Bucket, &i.TotalSeconds, &i.TaskCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalTaskDurations = `-- name: ListPersonalTaskDurations :many
SELECT
    CASE
        WHEN EXTRACT(EPOCH FROM (atq.completed_at - atq.started_at)) < 60    THEN 1
        WHEN EXTRACT(EPOCH FROM (atq.completed_at - atq.started_at)) < 300   THEN 2
        WHEN EXTRACT(EPOCH FROM (atq.completed_at - atq.started_at)) < 900   THEN 3
        WHEN EXTRACT(EPOCH FROM (atq.completed_at - atq.started_at)) < 1800  THEN 4
        ELSE 5
    END AS bucket,
    COUNT(*)::bigint AS task_count
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
WHERE a.workspace_id = $1
  AND atq.initiator_user_id = $2
  AND atq.status IN ('completed', 'failed')
  AND atq.started_at IS NOT NULL
  AND atq.completed_at IS NOT NULL
  AND atq.completed_at >= $3::timestamptz
  AND atq.completed_at <  $4::timestamptz
GROUP BY 1
ORDER BY 1
`

type ListPersonalTaskDurationsParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListPersonalTaskDurationsRow struct {
	Bucket    int32 `json:"bucket"`
	TaskCount int64 `json:"task_count"`
}

// Single-task run-time histogram buckets (1..5) over the current user's
// terminal tasks in the window. Tasks that never started (started_at NULL)
// have no duration and are excluded — they still show up in the summary's
// failure count. Bucket mapping (handled by the handler):
//
//	1 = <60s, 2 = 60-300s, 3 = 300-900s, 4 = 900-1800s, 5 = >1800s
func (q *Queries) ListPersonalTaskDurations(ctx context.Context, arg ListPersonalTaskDurationsParams) ([]ListPersonalTaskDurationsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalTaskDurations,
		arg.WorkspaceID,
		arg.UserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalTaskDurationsRow{}
	for rows.Next() {
		var i ListPersonalTaskDurationsRow
		if err := rows.Scan(&i.Bucket, &i.TaskCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalUsageModels = `-- name: ListPersonalUsageModels :many
SELECT
    LOWER(tu.provider) AS provider,
    tu.model,
    COALESCE(SUM(tu.input_tokens), 0)::bigint       AS input_tokens,
    COALESCE(SUM(tu.output_tokens), 0)::bigint      AS output_tokens,
    COALESCE(SUM(tu.cache_read_tokens), 0)::bigint  AS cache_read_tokens,
    COALESCE(SUM(tu.cache_write_tokens), 0)::bigint AS cache_write_tokens,
    COALESCE(SUM(tu.cost_usd_ticks), 0)::bigint AS cost_usd_ticks,
    COALESCE(SUM(tu.input_tokens)       FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_input_tokens,
    COALESCE(SUM(tu.output_tokens)      FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_output_tokens,
    COALESCE(SUM(tu.cache_read_tokens)  FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_cache_read_tokens,
    COALESCE(SUM(tu.cache_write_tokens) FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_cache_write_tokens,
    COUNT(DISTINCT atq.id)::bigint AS task_count
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
JOIN task_usage tu ON tu.task_id = atq.id
WHERE a.workspace_id = $1
  AND atq.initiator_user_id = $2
  AND atq.status IN ('completed', 'failed')
  AND atq.completed_at >= $3::timestamptz
  AND atq.completed_at <  $4::timestamptz
GROUP BY LOWER(tu.provider), tu.model
ORDER BY SUM(tu.input_tokens + tu.output_tokens + tu.cache_read_tokens + tu.cache_write_tokens) DESC,
         LOWER(tu.provider), tu.model
`

type ListPersonalUsageModelsParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListPersonalUsageModelsRow struct {
	Provider                 string `json:"provider"`
	Model                    string `json:"model"`
	InputTokens              int64  `json:"input_tokens"`
	OutputTokens             int64  `json:"output_tokens"`
	CacheReadTokens          int64  `json:"cache_read_tokens"`
	CacheWriteTokens         int64  `json:"cache_write_tokens"`
	CostUsdTicks             int64  `json:"cost_usd_ticks"`
	UncostedInputTokens      int64  `json:"uncosted_input_tokens"`
	UncostedOutputTokens     int64  `json:"uncosted_output_tokens"`
	UncostedCacheReadTokens  int64  `json:"uncosted_cache_read_tokens"`
	UncostedCacheWriteTokens int64  `json:"uncosted_cache_write_tokens"`
	TaskCount                int64  `json:"task_count"`
}

// Per-(provider, model) token + cost split over the current user's terminal
// tasks in the window. Provider rides along (LOWER-normalised) so bare model
// ids that collide across providers stay disambiguable, matching the
// workspace dashboard convention.
func (q *Queries) ListPersonalUsageModels(ctx context.Context, arg ListPersonalUsageModelsParams) ([]ListPersonalUsageModelsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalUsageModels,
		arg.WorkspaceID,
		arg.UserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalUsageModelsRow{}
	for rows.Next() {
		var i ListPersonalUsageModelsRow
		if err := rows.Scan(
			&i.Provider,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.CostUsdTicks,
			&i.UncostedInputTokens,
			&i.UncostedOutputTokens,
			&i.UncostedCacheReadTokens,
			&i.UncostedCacheWriteTokens,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalUsageTrendDaily = `-- name: ListPersonalUsageTrendDaily :many
SELECT
    DATE(atq.completed_at AT TIME ZONE $1::text) AS date,
    COALESCE(SUM(tu.input_tokens), 0)::bigint       AS input_tokens,
    COALESCE(SUM(tu.output_tokens), 0)::bigint      AS output_tokens,
    COALESCE(SUM(tu.cache_read_tokens), 0)::bigint  AS cache_read_tokens,
    COALESCE(SUM(tu.cache_write_tokens), 0)::bigint AS cache_write_tokens,
    COALESCE(SUM(tu.cost_usd_ticks), 0)::bigint AS cost_usd_ticks,
    COALESCE(SUM(tu.input_tokens)       FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_input_tokens,
    COALESCE(SUM(tu.output_tokens)      FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_output_tokens,
    COALESCE(SUM(tu.cache_read_tokens)  FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_cache_read_tokens,
    COALESCE(SUM(tu.cache_write_tokens) FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_cache_write_tokens,
    COUNT(DISTINCT atq.id)::bigint AS task_count
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
JOIN task_usage tu ON tu.task_id = atq.id
WHERE a.workspace_id = $2
  AND atq.initiator_user_id = $3
  AND atq.status IN ('completed', 'failed')
  AND atq.completed_at >= $4::timestamptz
  AND atq.completed_at <  $5::timestamptz
GROUP BY 1
ORDER BY 1
`

type ListPersonalUsageTrendDailyParams struct {
	Tz          string             `json:"tz"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListPersonalUsageTrendDailyRow struct {
	Date                     pgtype.Date `json:"date"`
	InputTokens              int64       `json:"input_tokens"`
	OutputTokens             int64       `json:"output_tokens"`
	CacheReadTokens          int64       `json:"cache_read_tokens"`
	CacheWriteTokens         int64       `json:"cache_write_tokens"`
	CostUsdTicks             int64       `json:"cost_usd_ticks"`
	UncostedInputTokens      int64       `json:"uncosted_input_tokens"`
	UncostedOutputTokens     int64       `json:"uncosted_output_tokens"`
	UncostedCacheReadTokens  int64       `json:"uncosted_cache_read_tokens"`
	UncostedCacheWriteTokens int64       `json:"uncosted_cache_write_tokens"`
	TaskCount                int64       `json:"task_count"`
}

// Per-calendar-day (viewer tz) token + cost split over the current user's
// terminal tasks. Powers the token/cost trend for `week` / `month` ranges.
func (q *Queries) ListPersonalUsageTrendDaily(ctx context.Context, arg ListPersonalUsageTrendDailyParams) ([]ListPersonalUsageTrendDailyRow, error) {
	rows, err := q.db.Query(ctx, listPersonalUsageTrendDaily,
		arg.Tz,
		arg.WorkspaceID,
		arg.UserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalUsageTrendDailyRow{}
	for rows.Next() {
		var i ListPersonalUsageTrendDailyRow
		if err := rows.Scan(
			&i.Date,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.CostUsdTicks,
			&i.UncostedInputTokens,
			&i.UncostedOutputTokens,
			&i.UncostedCacheReadTokens,
			&i.UncostedCacheWriteTokens,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalUsageTrendHourly = `-- name: ListPersonalUsageTrendHourly :many
SELECT
    DATE_TRUNC('hour', atq.completed_at AT TIME ZONE $1::text)::timestamp AS bucket,
    COALESCE(SUM(tu.input_tokens), 0)::bigint       AS input_tokens,
    COALESCE(SUM(tu.output_tokens), 0)::bigint      AS output_tokens,
    COALESCE(SUM(tu.cache_read_tokens), 0)::bigint  AS cache_read_tokens,
    COALESCE(SUM(tu.cache_write_tokens), 0)::bigint AS cache_write_tokens,
    COALESCE(SUM(tu.cost_usd_ticks), 0)::bigint AS cost_usd_ticks,
    COALESCE(SUM(tu.input_tokens)       FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_input_tokens,
    COALESCE(SUM(tu.output_tokens)      FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_output_tokens,
    COALESCE(SUM(tu.cache_read_tokens)  FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_cache_read_tokens,
    COALESCE(SUM(tu.cache_write_tokens) FILTER (WHERE tu.cost_usd_ticks IS NULL), 0)::bigint AS uncosted_cache_write_tokens,
    COUNT(DISTINCT atq.id)::bigint AS task_count
FROM agent_task_queue atq
JOIN agent a ON a.id = atq.agent_id
JOIN task_usage tu ON tu.task_id = atq.id
WHERE a.workspace_id = $2
  AND atq.initiator_user_id = $3
  AND atq.status IN ('completed', 'failed')
  AND atq.completed_at >= $4::timestamptz
  AND atq.completed_at <  $5::timestamptz
GROUP BY 1
ORDER BY 1
`

type ListPersonalUsageTrendHourlyParams struct {
	Tz          string             `json:"tz"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListPersonalUsageTrendHourlyRow struct {
	Bucket                   pgtype.Timestamp `json:"bucket"`
	InputTokens              int64            `json:"input_tokens"`
	OutputTokens             int64            `json:"output_tokens"`
	CacheReadTokens          int64            `json:"cache_read_tokens"`
	CacheWriteTokens         int64            `json:"cache_write_tokens"`
	CostUsdTicks             int64            `json:"cost_usd_ticks"`
	UncostedInputTokens      int64            `json:"uncosted_input_tokens"`
	UncostedOutputTokens     int64            `json:"uncosted_output_tokens"`
	UncostedCacheReadTokens  int64            `json:"uncosted_cache_read_tokens"`
	UncostedCacheWriteTokens int64            `json:"uncosted_cache_write_tokens"`
	TaskCount                int64            `json:"task_count"`
}

// Per-hour (viewer tz) token + cost split over the current user's terminal
// tasks. Powers the token/cost trend for the `today` range. The bucket comes
// back as a local wall-clock timestamp; the handler reinterprets it in the
// viewer tz before emitting (same convention as monitoring.go).
func (q *Queries) ListPersonalUsageTrendHourly(ctx context.Context, arg ListPersonalUsageTrendHourlyParams) ([]ListPersonalUsageTrendHourlyRow, error) {
	rows, err := q.db.Query(ctx, listPersonalUsageTrendHourly,
		arg.Tz,
		arg.WorkspaceID,
		arg.UserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalUsageTrendHourlyRow{}
	for rows.Next() {
		var i ListPersonalUsageTrendHourlyRow
		if err := rows.Scan(
			&i.Bucket,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.CostUsdTicks,
			&i.UncostedInputTokens,
			&i.UncostedOutputTokens,
			&i.UncostedCacheReadTokens,
			&i.UncostedCacheWriteTokens,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
